add day 43 task

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -22,15 +22,15 @@ jobs:
        if: failure()
        run: echo "Previous step failed....."
 
-  # on-push:
-  #   if: github.event_name != 'pull_request'
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: only run on push events
-  #       run: echo "Only run on push events"
+  on-push:
+    if: github.event_name != 'pull_request'
+    runs-on: ubuntu-latest
+    steps:
+      - name: only run on push events
+        run: echo "Only run on push events"
         
-  #     - name: step with continue-on-error
-  #       run: |
-  #         echo "This step will fail"
-  #         exit 1
-  #       continue-on-error: true
+      - name: step with continue-on-error
+        run: |
+          echo "This step will fail"
+          exit 1
+        continue-on-error: true
